#
---
services:
  acmecgi:
    image: acmecgi:0.2.1
    ports:
      - "10443:8443/tcp"
    env_file:
      - .env
    volumes:
      - ./pca:/app/pca
      - ./logs:/app/logs
      - ./config:/app/config

