# ACME.cgi httpd.conf

SERVER_NAME="acme.example.org"

server $SERVER_NAME {
	listen on * port 80
# handle any ACME challenges for this server when running an acme client
#	location "/.well-known/acme-challenge/*" {
#		root "/acme"
#		request strip 2
#	}
	# otherwise return a 302 redirect
	location * {
		block return 302 "https://$HTTP_HOST$REQUEST_URI"
	}
}

server $SERVER_NAME {
	listen on 127.0.0.1 tls port 443
	tls {
		certificate "/etc/ssl/"$SERVER_NAME".fullchain.pem"
		key "/etc/ssl/private/"$SERVER_NAME".key"
	}
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}

	location "/acme/*" {
		fastcgi {
			socket "/run/slowcgi.sock"
			param SCRIPT_FILENAME "/cgi-bin/ACME.cgi"
		}
	}
	# anything else just return error
	location * {
		block return 418 "I'm a teapot"
	}
}
