# Example httpd.conf
#
# Allow for server itself to get an ACME issued certificate.
#
server "acme.example.org" {
	listen on 0.0.0.0 tls port 80
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}
	location * {
		block return 302 "https://$HTTP_HOST$REQUEST_URI"
	}
}

server "acme.example.org" {
	listen on 0.0.0.0 tls port 443
	tls {
		certificate "/etc/ssl/acme.example.org.fullchain.pem"
		key "/etc/ssl/private/acme.example.org.key"
	}
	location "/acme/*" {
                fastcgi {
                        socket "/run/slowcgi.sock"
                        param SCRIPT_FILENAME "/cgi-bin/ACME.cgi"
                }
	}
}
